title: Alpha Business
description: "Alpha Business is een inspirerende kennismakingscursus met het christelijk geloof voor ondernemers, leiders en professionals in Lisse."
lang: nl

exclude:
  - CLAUDE.md
